package com.accenture.banking.model;
// Generated 11-may-2017 15:04:59 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AccountClientId generated by hbm2java
 */
@Embeddable
public class AccountClientId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private int accountId;
	private int clientId;

	public AccountClientId() {
	}

	public AccountClientId(int accountId, int clientId) {
		this.accountId = accountId;
		this.clientId = clientId;
	}

	@Column(name = "account_id", nullable = false)
	public int getAccountId() {
		return this.accountId;
	}

	public void setAccountId(int accountId) {
		this.accountId = accountId;
	}

	@Column(name = "client_id", nullable = false)
	public int getClientId() {
		return this.clientId;
	}

	public void setClientId(int clientId) {
		this.clientId = clientId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AccountClientId))
			return false;
		AccountClientId castOther = (AccountClientId) other;

		return (this.getAccountId() == castOther.getAccountId()) && (this.getClientId() == castOther.getClientId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getAccountId();
		result = 37 * result + this.getClientId();
		return result;
	}

}
