package com.accenture.banking.model;
// Generated 11-may-2017 15:04:59 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TransactionId generated by hbm2java
 */
@Embeddable
public class TransactionId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private int id;
	private int accountId;

	public TransactionId() {
	}

	public TransactionId(int id, int accountId) {
		this.id = id;
		this.accountId = accountId;
	}

	@Column(name = "id", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "account_id", nullable = false)
	public int getAccountId() {
		return this.accountId;
	}

	public void setAccountId(int accountId) {
		this.accountId = accountId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TransactionId))
			return false;
		TransactionId castOther = (TransactionId) other;

		return (this.getId() == castOther.getId()) && (this.getAccountId() == castOther.getAccountId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + this.getAccountId();
		return result;
	}

}
